/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frecuencia;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author benmu
 */
public class FrecuenciaApli extends javax.swing.JFrame {
    
    
    /**
     * Creates new form FrecuenciaApli
     */

    
    public FrecuenciaApli() {
        initComponents();
        this.setLocationRelativeTo(null);//Centro la ventana del interfaz en la pantalla.
        
       //TUBERÍA//
        InputStreamReader isr = new InputStreamReader(System.in);// Obtenemos el stream de lectura de la entrada estándar
        BufferedReader bf = new BufferedReader (isr);// Utilizamos un lector con Buffered, para no perder ningún dato
        String lineaTeclado = null;//Variable string nula.
        
        try
        {
            System.out.println("Proceso lector");//Mostramos que el proceso que está escribiendo es el que estáleyendo los datos.
            
            while ((lineaTeclado = bf.readLine())!= null)//Introduzco en la variable string el BufferedReader (información Generador)
            {
                cajaTex.setText(lineaTeclado);//Se obtiene la información del Generador y se plasma en la caja de texto de Frecuencia
            }
        }catch(IOException ex)//Excepciones en caso de errores
        {
            System.err.println("Se ha producido un error de E/S.");
            System.err.println(ex.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cajaTex = new javax.swing.JTextArea();
        resulA = new javax.swing.JTextField();
        resulE = new javax.swing.JTextField();
        resulO = new javax.swing.JTextField();
        okBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CONTAR LAS VOCALES \"A,E,O\" (MAYÚSCULAS COMO MINÚSCULAS.)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("TEXTO:");

        jLabel3.setText("El texto contiene un número de vocales \"a\":");

        jLabel4.setText("El texto contiene un númreo de vocales \"e\":");

        jLabel5.setText("El texto contiene un número de vocales \"o\":");

        cajaTex.setColumns(20);
        cajaTex.setLineWrap(true);
        cajaTex.setRows(5);
        jScrollPane1.setViewportView(cajaTex);

        okBoton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        okBoton.setText("OK");
        okBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(okBoton)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resulE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(resulA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(resulO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(okBoton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(resulA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(resulE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(resulO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBotonActionPerformed
        // TODO add your handling code here:
        
        //CONTAR LAS VOCALES//
        
        //Variables//
        int vocal_a=0, vocal_e=0, vocal_o=0;//Variables int para introducir los resultados de contar
        String texto=cajaTex.getText();//Se crea una variable String donde introduzco el texto introducido en la caja de texto
        int numero= cajaTex.getText().length();//Creo una variable int para introducir el numero de carateres del contenido de la caja texto.
        /*char[] caracteres= texto.toCharArray();*/
        
        //----------------------------------------------
        //                 Procesamiento
        //----------------------------------------------
        for (int i = 0; i < numero; i++){//For para hacer la cuenta de cada vocal
            if  ((texto.charAt(i)=='a')||(texto.charAt(i)=='A'))
            {
                vocal_a++;
            }
                                    
            if  ((texto.charAt (i)=='e')||(texto.charAt(i)=='E'))
            { 
                vocal_e++;
            }
            
            if  ((texto.charAt (i)=='o')||(texto.charAt(i)=='O'))
            {
                vocal_o++;
            }
        }
        
        //----------------------------------------------
        //                 Resultados
        //----------------------------------------------
        resulA.setText(String.valueOf(vocal_a));//Saco todos los resultados en sus respectivas cajas. Pasando a string el valor.
        resulE.setText(String.valueOf(vocal_e));
        resulO.setText(String.valueOf(vocal_o));
    }//GEN-LAST:event_okBotonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cajaTex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okBoton;
    private javax.swing.JTextField resulA;
    private javax.swing.JTextField resulE;
    private javax.swing.JTextField resulO;
    // End of variables declaration//GEN-END:variables
}
