/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lanzador;

import javax.swing.JOptionPane;

/**
 *
 * @author benmu
 */
public class LanzadorApli extends javax.swing.JFrame {

    /**
     * Creates new form LanzadorApli
     */
    public LanzadorApli() {
        initComponents();
        this.setLocationRelativeTo(null);//Centro el interfaz, para que al ejecutarlo me aparezca en el centro de la pantalla.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        okBoton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cuadroNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CREADOR DE PROCESOS DE \"GENERADOR\"");

        okBoton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        okBoton.setText("OK");
        okBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBotonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Elige el número de procesos del programa \"GENERADOR\" (De 0 a 10): ");
        jLabel2.setToolTipText("");

        cuadroNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuadroNumeroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(okBoton)
                            .addComponent(cuadroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cuadroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(okBoton)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuadroNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuadroNumeroKeyTyped
        // TODO add your handling code here:
        //Restriciones para la caja de texto
        char c = evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();

        if (cuadroNumero.getText().length()>=2)
        {
            evt.consume();
        }
    }//GEN-LAST:event_cuadroNumeroKeyTyped
    private boolean validarNumero ()//Establezco una clase para validar el número que se introducirá en la caja de procesos, de tal forma que aparecerán determinados paneles si no cumple los requisitos.
    {
        String num=cuadroNumero.getText();
        if (num==null||"".equals(num))
        {
            JOptionPane.showMessageDialog(this, "El número de procesos no puede estar vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        int numero= Integer.parseInt(cuadroNumero.getText());
            if (numero>10) 
        {
            JOptionPane.showMessageDialog(this, "Error. El número de procesos tiene que ser de 0 a 10", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
            return true;
    }
        
    private void okBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBotonActionPerformed
        // TODO add your handling code here:
        validarNumero();//Ejecuto la validación de número.
        int numero= Integer.parseInt(cuadroNumero.getText());//Creo una varible int para introducir el numero (string) escrito en el cuadro de texto del número de procesos
        if (numero<=10){for(int a = 0; a < numero; a++){//For para crear cada uno de los procesos. Procesos creados con Runtime y dos opciones de s.o, windosows y linux.
            Process nuevoProceso; //Definimos una variable de tipo Process
            try{
                String osName = System.getProperty("os.name");//Obtenemos el nombre del SO
                if (osName.toUpperCase().contains("WIN")){ //Windows
                    nuevoProceso = Runtime.getRuntime().exec("java -jar "+
                            "C:\\Mulero_Pedrosa_Benjamin_PSP01_Tarea\\Ejercicio_2\\Generador.jar");
                }else{//Linux
                    nuevoProceso = Runtime.getRuntime().exec("java -jar "+"/home/usuario/Generador.jar");
                }
            }catch (SecurityException ex){
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error de Seguridad.No se ha podido crear el proceso por falta de permisos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error, descripción: "+ex.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        }   
    }//GEN-LAST:event_okBotonActionPerformed
  
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cuadroNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okBoton;
    // End of variables declaration//GEN-END:variables
}
